### ISSUE TITLE
sync session between a users different devices

### ISSUE THREAD

**Issue by ghost** [Cretezy/redux_persist#11]
use case : If you sync the persisted redux between your many devices you could pick up where you left off on your other devices ?

**Comment by Cretezy** [comment]
That seems out of scope for `redux_persist`. The way to approach this would be to send the saved state to a server and grab in on load, but that's not the goal of this library, sorry! I'd be glad to guide you to making this though

**Comment by ghost** [comment]
I am doing the same using a golang server and NATS.

When a value is persisted it's sent also to the server. The NATS message queue then will push it to all your devices once they come online.

@cretezy
