### ISSUE TITLE
redux_persist <0.7.0-rc.1 is incompatible with redux_logging 0.3.0

### ISSUE THREAD

**Issue by hillelcoren** [Cretezy/redux_persist#14]
Thanks for creating this library!

I'm seeing the following error when trying to install it, I think upgrading to the latest version of redux should resolve it.

https://github.com/Cretezy/redux_persist/blob/master/packages/redux_persist/pubspec.yaml#L11
https://github.com/brianegan/redux_logging/blob/master/pubspec.yaml#L11

    Because redux_persist <0.7.0-rc.1 depends on redux ^2.1.1 and redux_logging 0.3.0 depends on redux 
    ^3.0.0, redux_persist <0.7.0-rc.1 is incompatible with redux_logging 0.3.0.
    And because no versions of redux_logging match >0.3.0 <0.4.0, redux_persist <0.7.0-rc.1 is incompatible with redux_logging ^0.3.0.

**Comment by Cretezy** [comment]
Actually, I just hadn't pushed `0.7.0-rc`'s code.

It requires `^3.0.0`: https://github.com/Cretezy/redux_persist/blob/master/packages/redux_persist/pubspec.yaml

Try using `0.7.0-rc.2`

**Comment by hillelcoren** [comment]
Thanks, it seems to be working now.

Not sure, I was just using `redux_persist: "^0.6.0"` per the docs.
