### ISSUE TITLE
FlutterSaveLocation is not exported in redux_persist_flutter

### ISSUE THREAD

**Issue by halldors** [Cretezy/redux_persist#15]
Hi, I cannot use sharedPreferences in version  0.6.0-rc.1 because it is not exported. I get this error

    compiler message: lib/app.dart:24:55: Error: The getter 'FlutterSaveLocation' isn't defined for the class '#lib1::_AppState'.
    compiler message: Try correcting the name to the name of an existing getter, or defining a getter or field named 'FlutterSaveLocation'.

**Comment by Cretezy** [comment]
https://github.com/Cretezy/redux_persist/blob/41667567cc347183c91ad2066cdcb18da2320a65/packages/redux_persist_flutter/lib/redux_persist_flutter.dart#L5

I believe you are importing it from the wrong file?

**Comment by halldors** [comment]
Thanks for that. But this has not been published then. This commit was made on May 2. However the latest version on pub.dartlang.org is 0.6.0-rc.1 and that was published on Mar 31. I will appreciate it if you could publish a new version with that fix. Thanks again.

**Comment by Cretezy** [comment]
The latest for `redux_persist` is `0.7.0-rc.2`, and for `redux_persist_flutter` is `0.6.0-rc`. Are you using those versions?

**Comment by halldors** [comment]
Yes, I'm using those versions.

redux_persist: "^0.7.0-rc.2"
redux_persist_flutter: "^0.6.0-rc.1"

<img width="934" alt="screen shot 2018-06-21 at 15 41 53" src="https://user-images.githubusercontent.com/16035199/41729818-be907dd8-7569-11e8-84ea-200df302d51d.png">

**Comment by bgetsug** [comment]
I'm experiencing the same issue. My workaround in `pubspec.yaml`:
```yaml
  redux_persist: "0.7.0-rc.2"
  redux_persist_flutter:
    git:
      url: git://github.com/Cretezy/redux_persist
      ref: master
      path: packages/redux_persist_flutter
```
I believe the `redux_persist_flutter` package needs to be published again, incrementing the version.

**Comment by Cretezy** [comment]
Yep, I'll republish soon. Thanks for the heads up!

**Comment by Cretezy** [comment]
Publish `0.7.0` and `0.6.0`!
