### ISSUE TITLE
Suggestion: Add in a Delay Option

### ISSUE THREAD

**Issue by ppeetteerrs-tinklabs** [Cretezy/redux_persist#17]
Would be nice if the PersistGate Widget accepts a delay parameter stating the duration that the splash screen should be visible for, or else the loading screen won't be shown most of the time.

**Comment by Cretezy** [comment]
Good idea!

**Comment by Cretezy** [comment]
Just as a bonus, if you do the initialization and wait before running `runApp`, it will stay using the default splash screen, making it seemless!

Flutter doesn't remove the default slash screen until `runApp` is ran.
