### ISSUE TITLE
Feature request: Option to check if the current action should trigger a save

### ISSUE THREAD

**Issue by Sh1d0w** [Cretezy/redux_persist#20]
Hello and thanks for the great plugin.

Looking at the source I don't see it possible to provide an option which returns true / false and controls the saving on the state based on that. The middleware intercepts every action, except the persist one and saves the store, which causes a lot of overheat especially if you are interested in saving only a part of your store.

As an example: in my app, the redux store consist of authToken, user, cart, isLoading, currentActiveTab, errorMessage and some pagination results. My AppState toJson returns a Map from auth, user and cart, as I want to persist the login state and the cart. The rest of the items has default values when you load the app again in the decode function, as I don't want to save the state of isLoading, errorMessage or other big chunks of data I don't need globally in the app.

Despite that, Persist save action is called on every action, triggering unnecessary writes to the disk, even if the changed state is not the one of that I am interested in.

My suggestion is to expose an option function which will receive the dispatched action in the middleware and return true or false. Based on that the middleware will save or skip saving the state to the disk.

**Comment by Cretezy** [comment]
Good idea. Do you have any ideas how to implement this?

What I'm thinking:
- Make a class type like `PersistSkip` with the getter `bool shouldSkip` (defaults to true)
- Make your actions which you don't want to extend `PersistSkip`
- The middleware will check if your action is of type PersistSkip, and will skip if `shouldSkip` is true

**Comment by Sh1d0w** [comment]
@Cretezy Thats sounds great!

**Comment by Cretezy** [comment]
Alright, I'll implement it.

I've restarted doing a lot more Flutter/Dart stuff in the past weeks and will definitely give a major overhaul to the library soon, this should be included.

**Comment by Sh1d0w** [comment]
For anyone having the same problem, before this gets implemented I've resolved it temporarily by adding my custom middleware, instead of `persistor.createMiddleware()` .

First create a placeholder class

`class NoPersist {}`

Then for actions you want to skip, just extend from this class.

In your store initialisation put this middleware:

```dart
(Store<AppState> store, dynamic action, NextDispatcher next) {
    var middleware = persistor.createMiddleware();

    if (action is! NoPersist) {
        try {
            // call the persister middleware
            middleware(store, action, next);
        } catch (_) {}
    } else {
        next(action);
    }
}
```

**Comment by gunhansancar** [comment]
@Sh1d0w Thanks for sharing your implementation. On my case I'd prefer to opposite version so instead of `NoPersist` I'd like to have `Persist` because there are usually a lot of unnecessary actions like loading, onerror, onresult, bla bla. actions which I don't want it to trigger any kind of savings. So I'll just do `if (action is Persist) {` and that'll do it.

**Comment by Cretezy** [comment]
This was added in 0.8.0-rc.0, let me know if that fixes your problem!
