### ISSUE TITLE
Save: Converting object to an encodable object failed: Instance of 'AppState'

### ISSUE THREAD

**Issue by osamagamal65** [Cretezy/redux_persist#21]
trying to use persist getting when dispatching any action I get this error 
Save: Converting object to an encodable object failed: Instance of 'AppState';

this is the presistor

`final persistor = new Persistor<AppState>(
    storage: new FlutterStorage('Pecards'), decoder: AppState.rehydrationJSON);
`

this is the app State model class 

`class AppState {
  final bool isLoading;

  final AuthState auth;
  final List<FullPeCard> pecards;
  final List<Request> requests;
  final List<Contact> contacts;
  final List<Chat> chats;
  final List<Ad> ads;
  final SimData simdata;
  final List<bool> appChecks;
  AppState(
      {this.auth,
      this.pecards = const [],
      this.contacts = const [],
      this.requests = const [],
      this.ads = const [],
      this.chats = const [],
      this.appChecks = const [false, false],
      this.isLoading = false,
      this.simdata});

static AppState rehydrationJSON(dynamic json) {
    return new AppState(
      auth: new AuthState.fromJSON(
        json['auth'],
      ),
      appChecks: json['appChecks'],
    );
  }
Map<String, dynamic> toJson() =>
      {'auth': auth.toJSON(), 'appChecks': appChecks};

  AppState copyWith({
    bool isLoading,
    bool rehydrated,
    bool openedFirstTime,
    AuthState auth,
    LoginForm loginForm,
    List<FullPeCard> pecards,
    List<Request> requests,
    List<Contact> contacts,
    List<Chat> chats,
    SimData simdata,
    List<Ad> ads,
    bool permissionsGranted,
  }) {
    return new AppState(
        auth: auth ?? this.auth,
        chats: chats ?? this.chats,
        contacts: contacts ?? this.contacts,
        requests: requests ?? this.requests,
        appChecks: appChecks ?? this.appChecks,
        pecards: pecards ?? this.pecards,
        isLoading: isLoading ?? this.isLoading,
        ads: ads ?? this.ads,
        simdata: simdata ?? this.simdata);
  }`

**Comment by Cretezy** [comment]
I think was fixed in 0.8.0-rc.0, let me know if that fixes your problem!
