### ISSUE TITLE
persistor.load() throws SerializationException when persistence file is nothing

### ISSUE THREAD

**Issue by nagoya0** [Cretezy/redux_persist#29]
Hi! Thanks for the great plugin.
I'm trying redux_persist 0.8.0-rc.1.
App throws SerializationException when persistence file is nothing such as app's first run.
Looks like returning null without exception is expected behavior according to sample codes.
```
E/flutter (28667): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (28667): SerializationException: On load: NoSuchMethodError: The method '[]' was called on null.
E/flutter (28667): Receiver: null
E/flutter (28667): Tried calling: []("var")
E/flutter (28667): #0      Persistor.load (package:redux_persist/src/persistor.dart:131:7)
E/flutter (28667): <asynchronous suspension>
E/flutter (28667): #1      main (xxx/lib/main.dart:17:40)
E/flutter (28667): <asynchronous suspension>
E/flutter (28667): #2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter (28667): #3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```
my code:
```
void main() async {
  final persistor = Persistor<AppState>(
    storage: FlutterStorage(),
    serializer: JsonSerializer<AppState>(AppState.fromJson),
  );

  final initialState = await persistor.load();    // throws SerializationException!!

  final store = Store<AppState>(
    appReducer,
    initialState: initialState ?? AppState.initial(),
    middleware: [persistor.createMiddleware()],
  );

  runApp(App(
      store: store,
  ));
}
```

**Comment by Cretezy** [comment]
Your JSON decoder function (`AppState.fromJson`) must be able to accept `null`, you'll most likely want to return an empty state.

**Comment by aurostudio** [comment]
@Cretezy: Can you give an example here for AppState.fromJson accepts null? I have the same issue, tried to accept the null as you mentioned but it doesn't help at all. Thanks!

**Comment by wuestkamp** [comment]
For me I need to pass a user, so my fromJson handles null like this:

```
class AppState {
  // !!!
  static AppState fromJson(dynamic json) {
    User initUser = json == null ? User() : json["user"];
    return AppState(initUser);
  }
```

**Comment by Cretezy** [comment]
Oh wow I have no clue how I never saw that comment. But yes, the above comment is right, just check if the param is null.

**Comment by amirfahmideh** [comment]
### I added factory to my AppState to support initial values
`factory AppState.loading() =>
      const AppState(count: 0, isLogin: false, authentication: null);`
### In fromJson of app state
`  factory AppState.fromJson(dynamic json) {
    if (json != null) {
      return _$AppStateFromJson(json);
    } else {
      return AppState.loading();
    }
  }`
