### ISSUE TITLE
On load: Concurrent modification during iteration: Instance(length:3) of '_GrowableList'.

### ISSUE THREAD

**Issue by inquisitev** [Cretezy/redux_persist#33]
void main() async{

  final persistor = Persistor<GMWAN_AppState>(
    storage: FlutterStorage(key: "GMWAN_AppState.json", location: FlutterSaveLocation.sharedPreferences), // Or use other engines
    serializer: JsonSerializer<GMWAN_AppState>(GMWAN_AppState.fromJson), // Or use other serializers
  );

  // Load initial state
/*

  final initalStateCompleter = Completer<dynamic>();

  persistor.load().then((store){
    initalStateCompleter.complete(store);
  }).catchError((c){
    print('ERRRRROOOOOORRRRRRR--------------------------------------------');
    initalStateCompleter.complete(GMWAN_AppState(userState: ParticleUserState(user: ParticleUser.notLoggedIn()),infoCardsState: InfoCardsState()));
  });

*/

  final initialState = await persistor.load();

  final store = new Store<GMWAN_AppState>(
      appStateReducer,
      initialState:
      initialState ?? GMWAN_AppState(userState: ParticleUserState(user: ParticleUser.notLoggedIn()),infoCardsState: InfoCardsState()),
      middleware: [thunkMiddleware, persistor.createMiddleware()]);

  runApp(StoreProvider<GMWAN_AppState>(
    child: MyApp(),
    store: store,
  ));
}

 Above is my main method. The thunk middle ware is an async network call that builds a list on response. 

[VERBOSE-2:shell.cc(186)] Dart Error: Unhandled exception:
SerializationException: On load: Concurrent modification during iteration: Instance(length:3) of '_GrowableList'.
#0      Persistor.load (package:redux_persist/src/persistor.dart:131:7)
<asynchronous suspension>
#1      main (package:gmwan/GMWAN_Redux/mainRedux.dart:37:40)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

Please advise on what i should do to fix this error. Thank you!

**Comment by Cretezy** [comment]
This seems to happen because you are calling `load` twice. Try with just one

**Comment by Cretezy** [comment]
Feel free to reopen the issue if this doesn't fix it!
