### ISSUE TITLE
Bump shared_preferences version

### ISSUE THREAD

**Issue by Sh1d0w** [Cretezy/redux_persist#34]
Hi,

When migration to AndroidX, there is a new shared_preferences version 0.5.0, but redux_persist version is pinned at 0.4.0 which causes dependencies to fail to install unless I override them with `dependencies_overrides`.

Can we get version bump, please?

**Comment by Cretezy** [comment]
Will do :+1: 

Are you sure you are installing 0.5.0 though? Because it's pinned at `^0.4.0`, which makes `0.5.0` compatible

**Comment by Cretezy** [comment]
Done with 0.8.1
