### ISSUE TITLE
Placeholder while state is loading

### ISSUE THREAD

**Issue by Sh1d0w** [Cretezy/redux_persist#35]
Hi,

with the old version 0.6.x we had PersistorGate which provided loading widget to display while state is loading.

With version 0.8.x of the package I see this was removed and now the state initialization must happen before you create your store and thus before rendering the initial root widget.

This is a deal breaker, why such a nice feature was removed and is there any possible workaround to show a placeholder widget before loading the state, so the user does not see a blank screen?

**Comment by Cretezy** [comment]
You can simply show something else while it's loading, it's super easy to do. I removed the PersistorGate **because** it was so easy to add.

Something like:
- Have a "App" component that called `persistor.load()` in `initState`
- Have a FutureBuilder that waits until it's loaded

**Comment by Sh1d0w** [comment]
@Cretezy that seems reasonable. Thanks!
