### ISSUE TITLE
Supporting asynchronous methods

### ISSUE THREAD

**Issue by jlcool** [Cretezy/redux_persist#42]
AppState.fromJson is an asynchronous method，I can't write it like this. How should I write it?
``` dart
    var p= Persistor<AppState>(
      storage: FlutterStorage(),
      serializer:  JsonSerializer((j) async {
        return await AppState.fromJson(j);
      }
    ),
    ) ;
```

**Comment by Cretezy** [comment]
How come is it asynchronous? Since it's just serializing, it should be synchronous, and you must do any async actions after loading (such as after doing `persistor.load()`, which will return the result of the serializer)

**Comment by jlcool** [comment]
Because I encrypt and decrypt the serialized data, and this encryption and decryption method is asynchronous, I am afraid that the serialized data will be modified, affecting software security.

**Comment by Cretezy** [comment]
That's supposed to be part of the storage instead. Copy/paste the FlutterStorage and add your encryption there

**Comment by jlcool** [comment]
Well, thank you

**Comment by Cretezy** [comment]
No problem! Let me know if you need any help. Feel free to create a package to let others use it too!
