### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by richie-south** [Cretezy/redux_persist#43]
Hey 👋 

Just wondering if this affects redux / flutter performance in any way? :)

**Comment by Cretezy** [comment]
It really shouldn't. The saving/loading is fully async, so disk operations are obviously off-thread, the biggest time spent is in parsing/stringifying, so small to medium states will be just fine and very fast, so unless you have a **huge** state (many MBs), it should be extremely quick.

If you need a huge state, I would recommend using SQLite instead, where you can load what you need as you go (more complex, but can be more performant)
