### ISSUE TITLE
Unhandled Exception: SerializationException: On load: NoSuchMethodError: The method '[]' was called on null in Flutter

### ISSUE THREAD

**Issue by ghost** [Cretezy/redux_persist#44]
Unhandled Exception: SerializationException: On load: NoSuchMethodError: The method '[]' was called on null in flutter.

my dependencies are: 

 flutter_redux: ^0.5.3
 redux_persist_flutter: ^0.8.1

**Comment by Cretezy** [comment]
Your `fromJson` method must be able to handle `null` if no state is present.
