### ISSUE TITLE
how to manually purge presisted data

### ISSUE THREAD

**Issue by TechGeekD** [Cretezy/redux_persist#49]
is there any method for manually purging persisted data, like for example clear persisted data when user signed out.

below is my persistor setup:
```
final persistor = Persistor<AppState>(
      storage: FlutterSecureStorageEngine(key: 'secureStore'),
      serializer: JsonSerializer<AppState>(AppState.fromJson),
      transforms: Transforms(
        onLoad: [
              (state) => state?.copyWith(
            homeState: state.homeState.copyWith(
              count: 0,
              loadingStatus: LoadingStatus.success,
            ),
            authState: state.authState.copyWith(
              loadingStatus: LoadingStatus.success,
            ),
          ),
        ],
      ),
      debug: true
);

// Load initial state
final initialState = await persistor.load();
```

**Comment by Cretezy** [comment]
This should automatically be handled, since your Redux state should be cleared when you logout

**Comment by TechGeekD** [comment]
Why I didn't think about this before, now it totally makes sense.

I had multiple reducers for different states respectively, but forgot to implement app level reducers which could have helped me reset state on log out, thanks 🙌.

**Comment by Cretezy** [comment]
No problem!
