### ISSUE TITLE
Dependency Conflict path_provider

### ISSUE THREAD

**Issue by dali546** [Cretezy/redux_persist#50]
the path provider plugin causes a dependency issue when other packages require 1.1.0
graphql uses the latest path provider, and there are some bug fixes that are in the latest release. 
```
pubspec.yaml
redux_persist_flutter: ^0.8.1
graphql_flutter: ^1.1.1-beta.7
```

```
Because graphql_flutter >=1.0.1-beta.8 depends on path_provider ^1.1.0 and redux_persist_flutter 0.8.1 depends on path_provider ^0.5.0+1, graphql_flutter >=1.0.1-beta.8 is incompatible with redux_persist_flutter 0.8.1.
And because no versions of redux_persist_flutter match >0.8.1 <0.9.0, graphql_flutter >=1.0.1-beta.8 is incompatible with redux_persist_flutter ^0.8.1.
So, because community depends on both redux_persist_flutter ^0.8.1 and graphql_flutter ^1.1.1-beta.7, version solving failed.
pub get failed (1)
```

is this possible to update?

**Comment by Cretezy** [comment]
Will do in next release 👍 

In the meantime you can override the package, and see if that works

**Comment by dali546** [comment]
well for now, I've removed your package (it's not greatly impacting my development as I am in early stages)

but hopefully soon it gets sorted. thanks

**Comment by ananaszjoe** [comment]
~~Can I ask for a release, so I could use the package with the compatible path_provider dependency?~~
**Edit:** If anyone wants to temporarily fetch the package from git instead of pub, can do so in their pubspec.yaml:
```
redux_persist_flutter:
    git:
      url: https://github.com/Cretezy/redux_persist.git
      path: packages/redux_persist_flutter
```

**Comment by Cretezy** [comment]
v0.8.2 is out fixing this.
