### ISSUE TITLE
 Error: Not found: 'dart:html'

### ISSUE THREAD

**Issue by redbluenat** [Cretezy/redux_persist#62]
Hi, 
I am using in my project **redux_persist_web** and **redux_persist**. Does anybody configured this to work on both platforms? When I want to build mobile version I get an error:

```
Compiler message:
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/redux_persist_web-0.8.2/lib/redux_persist_web.dart:4:8: Error: Not found: 'dart:html'
import 'dart:html';
```
 
My code at the moment :

```
import 'package:redux_persist/redux_persist.dart';
import 'package:redux_persist_web/redux_persist_web.dart' if (dart.library.html) 'package:redux_persist_web/redux_persist_web.dart';

final persistor = Persistor<AppState>(
    storage: kIsWeb ? WebStorage() : FileStorage(await _localFile),
    serializer: JsonSerializer<AppState>(AppState.fromJson);
  );
```

Thanks for any help!

**Comment by Cretezy** [comment]
You don't need `redux_persist_web` in this case.

`redux_persist_flutter` supports web on it's own (when using `FlutterStorage(location: FlutterSaveLocation.sharedPreferences)`).

I've added a note but haven't published an update yet, so Pub isn't updated yet

**Comment by redbluenat** [comment]
@Cretezy Thank you for your help! Everything is working now :)
