### ISSUE TITLE
Issue with Pubsec

### ISSUE THREAD

**Issue by neckaros** [Cretezy/redux_persist#7]
Hello,

When adding redux_persist in my pubsec as specifued on pub i get the following error:

```
  redux_persist: ^0.6.0
  redux_persist_flutter: ^0.5.0
```

```
Package redux_persist has no versions that match >=0.6.0 <0.7.0 derived from:
- project depends on version ^0.6.0
```

if i set no version it works but i get 0.7.0 rc1

**Comment by Cretezy** [comment]
This is pretty odd. It is working now?
