### ISSUE TITLE
 upgrade path_provider: 2.0.0

### ISSUE THREAD

**Issue by xiaocode337317439** [Cretezy/redux_persist#70]
Because redux_persist_flutter 0.8.3 depends on path_provider ^1.6.0 and no versions of redux_persist_flutter match >0.8.3 <0.9.0, redux_persist_flutter ^0.8.3 requires path_provider ^1.6.0.

**Comment by kevmeyer** [comment]
Resolved with https://github.com/Cretezy/redux_persist/pull/72
