### ISSUE TITLE
Undefined name 'FlutterSaveLocation'

### ISSUE THREAD

**Issue by giorgiogross** [Cretezy/redux_persist#8]
Hi,

I cannot access the FlutterSaveLocation enum, I think /packages/redux_persist_flutter/lib/redux_persist_flutter.dart should also include FlutterSaveLocation in its exported classes:
```
export 'src/storage.dart'
    show FlutterStorage, FlutterSaveLocation, DocumentFileEngine, SharedPreferencesEngine;
```
That way we can use the enum. If that's wrong: What would be the right solution to access the FlutterSaveLocation enum?

**Comment by Cretezy** [comment]
You're correct, I forgot to export it. Want to do a PR?
